const RESIGNATION_STATUS = Object.freeze(

    {
        PENDING: 'PENDING',
        MANAGER_APPROVED: 'MANAGER_APPROVED',
        MANAGER_REJECTED: 'MANAGER_REJECTED',
        HR_APPROVED: 'HR_APPROVED',
        HR_REJECTED: 'HR_REJECTED',
        EXIT_CLEARANCE: 'EXIT_CLEARANCE',
        FINAL_SETTLEMENT: 'FINAL_SETTLEMENT',
        COMPLETED: 'COMPLETED',
        CANCELLED: 'CANCELLED'
    }

);

module.exports = RESIGNATION_STATUS;